application: amcolash-iparkme
version: 1
runtime: python27
api_version: 1
threadsafe: no

#default_expiration: "30d"

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|manifest|woff))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|manifest|woff))

- url: /
  static_files: index.html
  upload: index.html
